name: Dispatch OpenAPI
on:
  workflow_dispatch:
  push:
    branches: [develop]
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: docs/openapi.yml

      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${PERSONAL_ACCESS_TOKEN}
        with:
          source_file: "docs/openapi.yml"
          destination_repo: "t-keshi/swagger-connect-fe"
          destination_folder: ""
          destination_branch: "develop"
          user_email: "quick.resp.biz094@gmail.com"
          user_name: "t-keshi"
          commit_message: "updated openapi"
          if: env.GIT_DIFF

      - name: Dispatch update-openapi
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: "t-keshi/swagger-connect-fe"
          token: ${PERSONAL_ACCESS_TOKEN}
          event-type: update-openapi
        if: env.GIT_DIFF
